name: Daily Salesforce Metadata Backup

on:
  schedule:
    - cron: "04 4 * * *" # every day at 2 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Salesforce CLI
    - name: Install Salesforce CLI
      run: npm install -g @salesforce/cli 
        
    - name: Authenticate to Salesforce
      run: |
         echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_SERVER_URL }} \
            --alias SFDC_v1 \
            --set-default
            
    - name: Retrieve metadata
      run: |
        mkdir -p manifest
        echo '<?xml version="1.0" encoding="UTF-8"?><Package xmlns="http://soap.sforce.com/2006/04/metadata"><types><members>*</members><name>ApexClass</name></types><types><members>*</members><name>CustomObject</name></types><version>58.0</version></Package>' > manifest/package.xml

        sf project retrieve start --metadata ApexClass

    - name: Commit and Push Changes
      run: |
        git config user.name "programmer-377"
        git config user.email "muthu19726@gmail.com"
        git add .
        git commit -m "Daily backup $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
